### ISSUE TITLE
Where is the game

### ISSUE THREAD

**Issue by xavxavier** [Neil0708/Trex-Game#1]
Where is the game. i need to steal it and make it my own smh

**Comment by Neil0708** [comment]
I accidently deleted it.... I just got a new mac for Christmas. The NEW mac
pro, for coding. And idk how to do stuff on it cuz it's my first mac and I
accidently deleted everything in that repository except for the title
hahahhahaha

**Comment by xavxavier** [comment]
sheeeeeesh hahahahahaha.

damn unlucky would have been so fun to steal. i mean play it hahaha 
have fun with the new mac lmaooo

**Comment by Neil0708** [comment]
what would u even do after stealing it.  i mean playing it

**Comment by xavxavier** [comment]
I would say its my own and that I have mastered js and the gaming js libary. Than i would get a job at one of the shitty flash game websites and say look im amazing hire me and that ill be rich. the end

**Comment by Neil0708** [comment]
if that happens. lemme live in ur house. ill pay rent at 50% discount
